export const ADD = "ADD";
export const SUB = "SUB";

export const FETCH_COVID_INFO_START = "FETCH_COVID_INFO_START";
export const FETCH_COVID_INFO_SUCCESS = "FETCH_COVID_INFO_SUCCESS";
export const FETCH_COVID_INFO_FAIL = "FETCH_COVID_INFO_FAIL";
